name: rose-dev
channels:
  - conda-forge
dependencies:
  # outut: metomi-rose-base
  - __unix
  - python >= 3.12.0
  - aiofiles
  - jinja2 >=2.10.1
  - keyring >=23
  - ldap3
  - metomi-isodatetime >=1!3.0,<1!4.0
  - psutil >=5.6.0
  - requests
  - sqlalchemy >=1,<2
  # - tornado (rosie disco is temporally disabled)

  # output: metomi-rose
  - pygraphviz >1.0,!=1.8
  - pygobject >=3.50.0
  - gtk3 >=3.24.43
  - libgirepository >=1.84.0
  - gobject-introspection >=1.84.0
  - cairo >=1.18.4
