[flake8]
exclude=
    .git,
    __pycache__,
    build,
    metomi/rose/etc/tutorial,
    ; purposely corrupt file
    t/rose-metadata-check/lib/custom_macro_corrupt.py,
    node_modules
    ;Temporary!
    metomi/rose/macros/rule.py
extend-select=
    ; Use `raise from` inside `except` for error handling
    ; https://docs.python.org/3/tutorial/errors.html#exception-chaining
    B904,
    ; Use Counter() instead of defaultdict(int) to avoid excessive memory use:
    B910
ignore=
    # for compliance with black:
    E203,
    # named lambdas sometimes used:
    E731,
    ; module level import not at top of file
    E402,
    ; line break before binary operator
    W503,
    ; line break after binary operator
    W504,
    ; "experimental" SIM9xx rules (flake8-simplify)
    SIM9,
    ; explicitly concatenated strings (flake8-implicit-str-concat)
    ISC003,
    ; not all exception subclass __init__ args passed to super __init__
    ; see https://github.com/cylc/cylc-flow/issues/7059
    B042,
    ; the module is shadowing a Python builtin module (May want to make temporary)
    A005,
    A004,
    A003,
    A001,
    ;Temporary!
    SIM115,
    B023
per-file-ignores=
    # Ignore suggestion for TYPE_CHECKING block in tests:
    metomi/*/tests/*: TC003
