#!/usr/bin/env python
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2012 Met Office.
# 
# This file is part of Rose, a framework for scientific suites.
# 
# Rose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Rose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Rose. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# NAME
#     rosa svn-post-commit
#
# SYNOPSIS
#     rosa svn-post-commit REPOS REV
#
# DESCRIPTION
#     Update the Rosie discovery database for an SVN changeset.
#-------------------------------------------------------------------------------

import os
import re
import shlex
import subprocess
import sys
import tempfile
import time

import sqlalchemy as al

import rose.config
from rose.resource import ResourceLocator

DATE_FMT = "%Y-%m-%d %H:%M:%S %Z"
RE_ID_NAMES = [r"[a-z]", r"[a-z]", r"\d", r"\d", r"\d"]
LEN_ID = len(RE_ID_NAMES)
INFO_FILE = "rose-suite.info"
KNOWN_KEYS_FILE = "rosie-keys"
REC_COPY_INFO = re.compile("^\s+\(from\s([^\s]+)\)$")
ST_ADDED = "A"
ST_DELETED = "D"
ST_MODIFIED = "M"


class DAO(object):

    """Data Access Object for 'put' type operations."""

    T_CHANGESET = "changeset"
    T_MAIN = "main"
    T_OPTIONAL = "optional"
    T_MODIFIED = "modified"
    T_META = "meta"
    
    def __init__(self, db_url):
        name = os.path.basename(repos).replace("roses_", "").replace("_svn", "")
        res_loc = ResourceLocator.default()
        url = res_loc.get_conf().get_value(["rosie-db", "db." + name])
        engine = al.create_engine(db_url)
        self.connection = engine.connect()
        self.metadata = al.MetaData(engine)
        self.tables = {}

    def _get_table(self, key):
        if not self.tables.has_key(key):
            self.tables[key] = al.Table(key, self.metadata, autoload=True)
        return self.tables[key]

    def delete(self, key, **kwargs):
        """Perform a delete on table key, using kwargs to select rows."""
        table = self._get_table(key)
        where = None
        for col, value in kwargs.items():
            if where is None:
                where = table.c[col] == value
            else:
                where &= table.c[col] == value
        statement = table.delete(whereclause=where)
        self.connection.execute(statement)

    def insert(self, key, **kwargs):
        """Insert values kwargs into table key."""
        statement = self._get_table(key).insert().values(**kwargs)
        self.connection.execute(statement)

    def update(self, key, where_match_cols, **kwargs):
        """Update the table 'key' with kwargs, using where_match_cols."""
        table = self._get_table(key)
        where = None
        for col in where_match_cols:
            if where is None:
                where = table.c[col] == kwargs[col]
            else:
                where &= table.c[col] == kwargs[col]
        statement = table.update(whereclause=where).values(**kwargs)
        self.connection.execute(statement)


def svnlook(*args):
    """Return the standard output from "svnlook"."""
    p = subprocess.Popen(["svnlook"] + list(args), stdout=subprocess.PIPE)
    (out, err) = p.communicate()
    rc = p.wait()
    if rc:
        sys.exit("[FAIL] %s # rc=%d" % (" ".join(["svnlook"] + list(args)), rc))
    return out


def check_path_is_idx(path):
    """Return whether the path contains a full idx."""
    names = path.split("/")
    if len(names) < LEN_ID + 1:
        return False
    if "".join(names)[:LEN_ID] == "ROSIE":
        return True
    for name, pattern in zip(names, RE_ID_NAMES):
        if not re.compile(r"\A" + pattern + r"\Z").match(name):
            return False
    return True


def main(repos, rev):
    db_name = os.path.basename(repos).replace("roses_", "").replace("_svn", "")
    conf = ResourceLocator.default().get_conf()
    dao = DAO(conf.get_value(["rosie-db", "db." + db_name]))
    statuses = {}
    copies = {}
    author = svnlook("author", "-r", rev, repos).strip()
    os.environ["TZ"] = "" # ensure UTC
    d, t, junk = svnlook("date", "-r", rev, repos).split(None, 2)
    date = time.mktime(time.strptime(" ".join([d, t, "UTC"]), DATE_FMT))

    path_copies = {}
    path_num = 0
    copy_changes = svnlook("changed", "--copy-info", "-r", rev, repos)
    for i, change in enumerate(copy_changes.splitlines()):
        copy_match = REC_COPY_INFO.match(change)
        if copy_match:
            path_copies[path_num] = copy_match.groups()[0]
        else:
            path_num += 1
    changes = svnlook("changed", "-r", rev, repos)
    for i, line in enumerate(changes.splitlines()):
        status, path = line.split(None, 1)
        if not check_path_is_idx(path):
            continue
        names = path.split("/")
        idx = "".join(names[0:LEN_ID])
        branch = names[LEN_ID]
        if i in path_copies and check_path_is_idx(path_copies[i]):
            copy_names = path_copies[i].split("/")
            copy_idx = "".join(copy_names[:LEN_ID])
            if copy_idx != idx:
                copies.setdefault((rev, idx, branch), copy_idx)
        
        if branch:
            statuses.setdefault((rev, idx, branch), {0: " ", 1: " "})
        branch_path = "/".join(idx) + "/" + branch
        info_file_path = branch_path + "/" + INFO_FILE
        if not branch and status[0] == ST_DELETED:
            out = svnlook("tree", "-r", str(int(rev) - 1), "-N", repos, path)
            for line in out.splitlines()[1:]:
                del_branch = line.strip().rstrip("/")
                statuses.setdefault((rev, idx, del_branch), {0: " ", 1: " "})
                statuses[(rev, idx, del_branch)][0] = ST_DELETED
 
        if (idx == "ROSIE" and branch == "trunk" and
            path == branch_path + "/" + KNOWN_KEYS_FILE):
            new_keys = parse_known_keys(repos, path, rev)
            if new_keys is not None:
                try:
                    dao.insert(dao.T_META, name="known_keys", value=new_keys)
                except al.exc.IntegrityError:
                    dao.update(dao.T_META, ("name",), name="known_keys", value=new_keys)

        if path.rstrip("/") == branch_path:
            if status[0] == ST_DELETED:
                statuses[(rev, idx, branch)][0] = ST_DELETED
                continue
            if status[0] == ST_ADDED:
                statuses[(rev, idx, branch)][0] = ST_ADDED
        if (len(path) > len(branch_path) and path != info_file_path and
            statuses[(rev, idx, branch)][0].isspace()):
            statuses[(rev, idx, branch)][0] = ST_MODIFIED
        if status[0] == ST_DELETED or path != info_file_path:
            continue
        
        f = tempfile.TemporaryFile()
        f.write(svnlook("cat", "-r", rev, repos, path))
        f.seek(0)
        config = rose.config.load(f)
        f.close()
        
        if status[0] == ST_ADDED:
            old_config = rose.config.ConfigNode()
        else:
            f = tempfile.TemporaryFile()
            f.write(svnlook("cat", "-r", str(int(rev) -1), repos, path))
            f.seek(0)
            old_config = rose.config.load(f)
            f.close()

        items = {"revision": rev, "idx": idx, "branch":branch}
        for key, node in old_config.value.items():
            if node.is_ignored():
                continue
            new_node = config.get([key], no_ignore=True)
            if new_node is None:
                statuses[(rev, idx, branch)].update({1: ST_MODIFIED})
                dao.insert(dao.T_MODIFIED, name=key, old_value=node.value,
                           new_value=None, **items)
                if key not in ["owner", "project", "title"]:
                    dao.delete(dao.T_OPTIONAL, idx=idx, branch=branch, name=key)
            elif node.value != new_node.value:
                statuses[(rev, idx, branch)].update({1: ST_MODIFIED})
                dao.insert(dao.T_MODIFIED, name=key, old_value=node.value,
                           new_value=new_node.value, **items)
                if key not in ["owner", "project", "title"]:
                    dao.update(dao.T_OPTIONAL, ("idx", "branch", "name"),
                               idx=idx, branch=branch, name=key,
                               value=new_node.value)
        for key, node in config.value.items():
            if node.is_ignored():
                continue
            old_node = old_config.get([key], no_ignore=True)
            if old_node is None:
                statuses[(rev, idx, branch)].update({1: ST_MODIFIED})
                dao.insert(dao.T_MODIFIED, name=key, old_value=None,
                           new_value=node.value, **items)
                if key not in ["owner", "project", "title"]:
                    dao.insert(dao.T_OPTIONAL, idx=idx, branch=branch,
                               name=key, value=node.value)
                
        items = {}
        for key in ["owner", "project", "title"]:
            items[key] = config.get([key], no_ignore=True).value
        if status == ST_ADDED:
            try:
                dao.insert(dao.T_MAIN, idx=idx, branch=branch, **items)
            except al.exc.IntegrityError:
                dao.update(dao.T_MAIN, ("idx", "branch"), idx=idx, branch=branch,
                           **items)
        else:
            dao.update(dao.T_MAIN, ("idx", "branch"), idx=idx, branch=branch,
                       **items)

    # End loop over changes, update statuses.
    for key, value in statuses.items():
        rev, idx, branch = key
        copy_idx = copies.get(key)
        status = ""
        if value[0] == ST_ADDED:
            value[1] = " "
        for num in sorted(value.keys()):
            status += value[num]
        if not (status.isspace() and copy_idx is None):
            dao.insert(dao.T_CHANGESET, revision=rev, idx=idx,
                       branch=branch, author=author, date=date,
                       status=status, from_idx=copy_idx)


def parse_known_keys(repos, file_path, rev):
    """Parse the file containing whitespace-separated known keys."""
    key_string = svnlook("cat", "-r", rev, repos, file_path)
    return " ".join(shlex.split(key_string))


if __name__ == "__main__":
    repos, rev = sys.argv[1:3]
    main(repos, rev)
