meta=rose_bunch
mode=rose_bunch

[bunch]
command-format=echo arg1: %(arg1)s, arg2: %(arg2)s, command-instance: %(command-instances)s
command-instances = 4
incremental = true
names-from-args = true

[bunch-args]
arg1=test1 test2 test3 test4
arg2=foo bar baz qux
