#!/bin/bash
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2012-6 Met Office.
#
# This file is part of Rose, a framework for meteorological suites.
#
# Rose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rose. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# Provides init, setup and teardown functions for rose app-run tests.
#-------------------------------------------------------------------------------
. $(dirname $0)/../lib/bash/test_header

function test_init() {
    mkdir -p $TEST_DIR/config
    cat >$TEST_DIR/config/rose-app.conf
}

function test_setup() {
    mkdir $TEST_DIR/run
    cd $TEST_DIR/run
}

function test_teardown() {
    cd $TEST_DIR
    rm -rf $TEST_DIR/run
}
