#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# Copyright (C) 2012-2019 British Crown (Met Office) & Contributors.
#
# This file is part of Rose, a framework for meteorological suites.
#
# Rose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rose. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

# Bash script for use with Travis-CI builds.
#
# usage: now command [args...]
#
# commands:
#     build
#     install
#     report_coverage
#     test

# source the .bashrc because for some reason this doesn't get done for us
# do this before the set -eu to avoid bailing on the build for hardcoded
# bashrc issues
if [[ -f "${HOME}/.bashrc" ]]; then
    source "${HOME}/.bashrc"
fi


set -eu

APT=()
NPM=()
PIP=()
GIT=()
PY_PATH=()
RC_PATH=("${HOME}")
RI_PATH=()
WANDISCO=false


_build_docs () {
    etc/bin/rose-make-docs --strict clean html slides latexpdf
}

_gh_extract () {  # extract project from GitHub to $HOME
    IFS='|' read -ra SPEC <<< "$1"
    local USR="${SPEC[0]}"
    local REPO="${SPEC[1]}"
    local BRANCH="${SPEC[2]}"
    local URL="https://github.com/${USR}/${REPO}/archive/${BRANCH}.tar.gz"
    local DEST="${HOME}/${REPO}-${BRANCH}"

    if [[ -d "${DEST}" ]]; then
        # already installed
        return
    fi

    # download + unpack
    wget "${URL}" -O - | tar -xz -C "${HOME}"

    # in-place installation
    if [[ -f "${DEST}/setup.py" ]]; then
        pip install -e "${DEST}"
    fi
}

_install_coverage () {
    PIP+=(coverage pytest-cov)
    PY_PATH+=("${TRAVIS_BUILD_DIR}/.travis")
}

_install_rose () {
    pip install -e .
    PY_PATH+=("${TRAVIS_BUILD_DIR}/metomi")
    RC_PATH+=("${TRAVIS_BUILD_DIR}/bin")
}

_install_cylc () {
    APT+=(at)
}

_install_fcm () {
    APT+=(subversion build-essential gfortran libxml-parser-perl \
          libconfig-inifiles-perl libdbi-perl libdbd-sqlite3-perl)
    GIT+=('metomi|fcm|master')
    RC_PATH+=("${HOME}/fcm-master/bin")
    WANDISCO=true
}

_install_pytest () {
    # pytest and its extensions
    PIP+=(pytest)
}

_install_rosie () {
    PIP+=(requests tornado sqlalchemy)
    RI_PATH+=("$(_path_for python)" "$(_path_for rose)")
}

_install_sphinx () {
    # sphinx documentation and its extensions
    APT+=(latexmk texlive texlive-generic-extra texlive-latex-extra \
          texlive-fonts-recommended graphviz)
    pip install -e .[docs]
}

_install_tut_suite () {
    # cylc tutorial suite
    PIP+=(pillow)
}

_join () {
    local IFS="$1";
    shift;
    echo "$*";
}

_install_linters () {
    APT+=(shellcheck)
    PIP+=(pycodestyle)
    NPM+=(eslint)
}

_path_for () {
    COMMAND="$1"
    dirname "$(command -v "${COMMAND}")"
}

_test_units () {
    pytest --cov-append metomi/rose/tests/*
}

_test_style () {
    pycodestyle
    eslint .
    "$(dirname "$0")/shellchecker"
}

_test_battery () {
    cp "${TRAVIS_BUILD_DIR}/.travis/sitecustomize.py" ./lib/python
    coverage run .travis/cover.py
}

_test_docs () {
    etc/bin/rose-make-docs --strict clean linkcheck doctest
}

_wandisco_configure () {  # extract Wandisco stuff
    # shellcheck disable=SC1004,SC2016
    sudo sh -c 'echo "deb http://opensource.wandisco.com/ubuntu \
        `lsb_release -cs` svn19" >> /etc/apt/sources.list.d/subversion19.list'
    sudo wget -q http://opensource.wandisco.com/wandisco-debian.gpg -O- | \
        sudo apt-key add -
}

build () {
    for arg in "$@"; do
        "_build_${arg}"
    done
}

    # shellcheck disable=SC2032
install () {
    for arg in "$@"; do
        "_install_${arg}"
    done

    if ${WANDISCO}; then
        _wandisco_configure
    fi

    if [[ ${#PIP[@]} -gt 0 ]]; then
        pip install "${PIP[@]}" &
    fi

    if [[ ${#NPM[@]} -gt 0 ]]; then
        npm install -g "${NPM[@]}" &
    fi

    if [[ ${#APT[@]} -gt 0 ]]; then
        sudo apt-get update
        # shellcheck disable=SC155,2033
        sudo apt-get install -y "${APT[@]}"
    fi

    if [[ ${#GIT[@]} -gt 0 ]]; then
        # wrapping the for loop to avoid unbound variable "GIT[@]" error
        for gh_project in "${GIT[@]}"; do
            _gh_extract "${gh_project}"
        done
    fi

    wait

    # .bashrc
    cat >"${HOME}/.bashrc" \
        <<<"export PATH=\"$(_join ':' "${RC_PATH[@]}"):\$PATH\";"
    cat >>"${HOME}/.bashrc" \
        <<<"export PYTHONPATH=\"$(_join ':' "${PY_PATH[@]}"):\$PYTHONPATH\";"

    # rose_init_site
    cat >"${TRAVIS_BUILD_DIR}/lib/bash/rose_init_site" \
        <<<"
            if [[ -z \${HOME+x} ]]; then
                export PATH=\"$(_join ':' "${RI_PATH[@]}"):\${PATH:-}\";
            fi
        "
}

_report_coverage () {
    coverage combine --append
    coverage xml --ignore-errors
    bash <(curl -s https://codecov.io/bash)
}

_report_error() {
    # don't bail out on error
    set +eu

    printenv PATH PYTHONPATH
    rose check-software
    cat /tmp/sphinx-err* >&2 # sphinx traceback
}

report () {
    for arg in "$@"; do
        "_report_${arg}"
    done
}

test () {
    PS1='$' . "${HOME}/.bashrc"
    export COVERAGE_PROCESS_START="${TRAVIS_BUILD_DIR}/.coveragerc"
    for arg in "$@"; do
        "_test_${arg}"
    done
}

# do this here so we only trace the commands we are interested in
set -o xtrace

# run the specified function
"$@"
