#!/bin/bash
#-------------------------------------------------------------------------------
# Copyright (C) 2012-2019 British Crown (Met Office) & Contributors.
#
# This file is part of Rose, a framework for meteorological suites.
#
# Rose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rose. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# NAME
#     rose_init
#
# SYNOPSIS
#     . $ROSE_HOME/lib/bash/rose_init
#     rose_init [FUNC ...]
#
# DESCRIPTION
#     Initialise a bash script with the following:
#     * "set -eu".
#     * load the "rose_usage" function.
#     * load any FUNC specified in the argument list.
#-------------------------------------------------------------------------------
# shellcheck source=lib/bash/rose_usage
. rose_usage

function rose_init() {
    set -eu
    ROSE_NS=$(basename "$0")
    ROSE_LIB="$(dirname "$(python -c "import metomi.rose; print(metomi.rose.__file__)")")"
    ROSE_HOME_BIN=$(dirname "$(command -v rose)")
    ROSE_VERSION="$(python3 -c "import metomi.rose; print(metomi.rose.__version__)")"
    export ROSE_LIB ROSE_HOME_BIN ROSE_NS ROSE_VERSION
    local LIB=$ROSE_LIB
    if [[ -f $LIB/${FUNCNAME[0]}_site ]]; then
        . "$LIB/${FUNCNAME[0]}_site"
    fi

    local ITEM=
    for ITEM in rose_usage "$@"; do
        local FILE=
        for FILE in $ITEM; do
            . "$FILE"
        done
    done
}
