#!/bin/bash
#-------------------------------------------------------------------------------
# (C) British Crown Copyright 2012 Met Office.
# 
# This file is part of Rose, a framework for scientific suites.
# 
# Rose is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Rose is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Rose. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
# NAME
#     rose_init_site
#
# SYNOPSIS
#     . $ROSE_HOME/lib/bash/rose_init_site
#
# DESCRIPTION
#     Ugly part of rose_init. Implements site specified settings that need to be
#     configured before "rose config" can even be used.
#-------------------------------------------------------------------------------
# Met Office HPC IBM Power 6: requires this version of python.
if [[ ${PATH:-} != */opt/python/2.6.6/bin:* && -d /opt/python/2.6.6/bin ]]; then
    PATH=/opt/python/2.6.6/bin:$PATH
fi
# Some Python modules are installed here.
if [[ -z ${PYTHONPATH:-} ]]; then
    PYTHONPATH=~fcm/lib/python
elif [[ ${PYTHONPATH:-} != *~fcm/lib/python:* && -d ~fcm/lib/python ]]; then
    PYTHONPATH=~fcm/lib/python:$PYTHONPATH
fi
export PATH PYTHONPATH
