name: Sync PR

on:
  push:
    branches:
      - '2.*.x'
  schedule:
    - cron: '13 05 * * 1,3,5' # 05:13 UTC Mon,Wed,Fri
  workflow_dispatch:
    inputs:
      head_branch:
        description: Branch to merge into master
        required: true

jobs:
  sync:
    uses: cylc/release-actions/.github/workflows/branch-sync.yml@v1
    with:
      head_branch: ${{ inputs.head_branch }}
      ignore_branches: 2019.01.x
    secrets: inherit
