name: test rsync remote check

on:
  pull_request:
  workflow_dispatch:
    inputs:
      rose_ref:
        description: The Rose branch to test against
        required: true
      fcm_ref:
        description: The FCM branch to test against
        required: false
      fcm_repo:
        description: The FCM repo to test against
        required: false
      cylc_ref:
        description: The Cylc branch to test against
        required: false
      cylc_repo:
        description: The Cylc repo to test against
        required: false

defaults:
  run:
    shell: bash  # macos default shell is zsh

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [
          '2.7',
          '3.0', '3.1', '3.2', '3.3', '3.4', '3.5', '3.6',
          '3.7', '3.8', '3.9'
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rose_ref || github.sha }}
          path: rose

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Rsync Remote
        working-directory: rose
        run: |
          pip install pytest
          pytest metomi/rose/tests/test_loc_handlers_rsync_remote_check.py
